add_newline = false

format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "git "
style = "yellow"

[git_status]
style = "red"
